Added Lightrun and debugging/APM section
agamm/awesome-developer-first pull request #10
Opened 2021-07-12 02:06 UTC by shai-almog

2021-08-02 22:31 UTC, agamm commented
I would add this to monitoring or open a new debugging category with competitors (I don't like to open a category without any other tools). I see there is also Rookout in the same space.

2021-08-03 01:29 UTC, shai-almog commented
Good point. I'm not familiar enough with Ozcode to write anything about it and their website is a bit ambiguous about the technology so I left it out. But I do know the google cloud solution and rookout which I added.

2021-08-03 07:51 UTC, agamm requested changes
Added some grammar fixes and a question about the GCP solution.

2021-08-03 07:51 UTC, agamm commented on README.md
> +* [Google Cloud's operations suite](https://cloud.google.com/products/operations) -  Set of debug primitives (capture, log injection etc) for Google cloud
```suggestion
* [Google Cloud's operations suite](https://cloud.google.com/products/operations) -  Set of debug primitives (capture, log injection, etc) for Google cloud.
```

2021-08-03 07:51 UTC, agamm commented on README.md
> +* [Google Cloud's operations suite](https://cloud.google.com/products/operations) -  Set of debug primitives (capture, log injection etc) for Google cloud
Are you sure this is a widely known solution? I mean if people use this they don't need to use the other ones? plus it only seems to be relevant to GCP, no?

2021-08-03 07:51 UTC, agamm commented on README.md
> +* [Lightrun](https://www.lightrun.com) - Debug production servers using a plugin in the IDE (on prem or SaaS) supports Java, Node.js and Python
```suggestion
* [Lightrun](https://www.lightrun.com) - Debug production servers using a plugin in the IDE (on-prem or SaaS) that supports Java, Node.js, and Python.
```

2021-08-03 07:51 UTC, agamm commented on README.md
> +* [Rookout](https://www.rookout.com) - Debug production servers via cloud based debugger. Supports Java, .Net, Node.js, Python, and Ruby
```suggestion
* [Rookout](https://www.rookout.com) - Debug production servers via a cloud-based debugger. Supporting Java, .Net, Node.js, Python, and Ruby.
```

2021-08-03 07:52 UTC, agamm commented on README.md
> +* [Rookout](https://www.rookout.com) - Debug production servers via cloud based debugger. Supports Java, .Net, Node.js, Python, and Ruby
Does rookout also support on-prem in some way? what is the other difference from lightrun? (to be consistent with the "on-prem or SaaS" you wrote :)

2021-08-03 08:02 UTC, shai-almog commented on README.md
> +* [Rookout](https://www.rookout.com) - Debug production servers via cloud based debugger. Supports Java, .Net, Node.js, Python, and Ruby
Rookout supports more platforms and has been around longer. It's a cloud based solution so while it does have an IDE plugin it's main focus is on debugging via the web interface.  It doesn't have an on-prem option but it does have a locally installed proxy option. I'm not sure if that can be considered on-prem.

The three tools are conceptually similar. They try to provide the power of debugging local applications on a production server securely. Their approaches are also similar: agent installed on your server connected to their backend. The differences are:

- Agent implementations - this varies a bit but is too subjective to quantify so not relevant here
- Languages supported
- Vendor specific - Google only runs on GCP as far as I know
- IDE integration vs. Web App
- On-prem vs. SaaS - AFAIK only Lightun offers an on-prem option

2021-08-03 08:05 UTC, agamm commented on README.md
> +* [Rookout](https://www.rookout.com) - Debug production servers via cloud based debugger. Supports Java, .Net, Node.js, Python, and Ruby
Awesome, thanks for the clarification. Let's commit the grammar changes and merge?

2021-08-03 08:08 UTC, shai-almog commented on README.md
> +* [Google Cloud's operations suite](https://cloud.google.com/products/operations) -  Set of debug primitives (capture, log injection etc) for Google cloud
The GCP option is pretty widely known. It's mostly known as stackdriver but Google renamed it recently.

2021-08-03 08:09 UTC, shai-almog commented on README.md
> +* [Rookout](https://www.rookout.com) - Debug production servers via cloud based debugger. Supports Java, .Net, Node.js, Python, and Ruby
Sorry I thought I committed that, should be done now.

2021-08-03 08:23 UTC, agamm approved these changes
Awesome, thanks for the participation and responsiveness :)

2021-08-03 08:24 UTC, merged