Added EmailEngine
agamm/awesome-developer-first pull request #28
Opened 2022-02-14 12:55 UTC by andris9

EmailEngine allows accessing email accounts using a REST API instead of IMAP

2022-02-19 04:18 UTC, agamm requested changes
Thanks for the contribution, looks like a great tool. 
It is quite the oddball here in the SaaS space :) but it still complies with the contribution guide, so I'll accept it.
Also, I would move this to the `Mail` category.
I'll change the description to make it work.

2022-02-19 04:18 UTC, agamm commented on README.md
> +* [EmailEngine](https://emailengine.app/) - API and webhooks for existing email accounts
```suggestion
* [EmailEngine](https://emailengine.app/) - API and webhooks for existing email accounts (IMAP & SMTP).
```

2022-03-16 10:32 UTC, agamm commented on README.md
> +* [EmailEngine](https://emailengine.app/) - API and webhooks for existing email accounts
@andris9 ?

2022-03-16 10:44 UTC, andris9 commented on README.md
> +* [EmailEngine](https://emailengine.app/) - API and webhooks for existing email accounts
Looks great 👍

2022-03-16 11:22 UTC, agamm commented
@andris9 Can you move it to the mail category?

2022-03-24 13:13 UTC, agamm commented
@andris9 ?

2022-04-13 15:33 UTC, agamm commented
@andris9 shall I close or are we changing it?

2022-05-15 23:51 UTC, agamm commented
Closing until there is a response 👀

2022-05-15 23:51 UTC, closed without merging