Adds Docraptor HTML to PDF API, take 2
agamm/awesome-developer-first pull request #35
Opened 2022-05-16 19:32 UTC by JamesPaden

Duplicate of now closed #30 

The contribution guide requested the "most awesome" services, but I wasn't sure how much detail to put in the listing description. The tl;dr is that DocRaptor is the only API that uses the [Prince](https://www.princexml.com/) library which lets us do waaaaay more advanced stuff than browser-based HTML to PDF generatosr. Lot of print-specific kinds of [details](https://docraptor.com/samples), such as CMYK support, TIFF images, different headers and footers throughout the document, float-to-the-top-of-the-page, etc, etc. And solely targeted at developers with lots of code samples and agent libraries.

Apologies for opening a second PR. I expected the previous one to update when I updated the fork, but it did not.

2022-05-18 20:46 UTC, agamm requested changes
I edited a tiny bit.

2022-05-18 20:46 UTC, agamm commented on README.md
> +* [DocRaptor[(https://docraptor.com) - HTML to PDF API built specifically for Paged Media using the Prince PDF library
```suggestion
* [DocRaptor[(https://docraptor.com) - HTML to PDF API built specifically for Paged Media using the [Prince](https://www.princexml.com/) PDF library.
```

2022-05-20 14:12 UTC, JamesPaden commented
Looks great to me, thanks!

2022-05-21 21:49 UTC, agamm approved these changes

2022-05-21 21:50 UTC, merged