Added GrowthBook to Feature Flags
agamm/awesome-developer-first pull request #39
Opened 2022-09-29 21:21 UTC by Auz

2022-10-01 23:08 UTC, agamm requested changes
Please insert the addition at the bottom of the list ;)

2022-10-07 15:00 UTC, agamm commented
@Auz

2022-10-28 19:39 UTC, Auz commented
Moved to the bottom of the list

2022-10-28 19:55 UTC, agamm approved these changes
Thanks!

2022-10-28 19:55 UTC, merged