Add Environment Variables Section
agamm/awesome-developer-first pull request #4
Opened 2021-03-11 06:39 UTC by bvallelunga

2021-05-30 09:41 UTC, agamm commented
Hi @bvallelunga in order to merge a new section we need to see at least 2 products in the subject, do you know another one?

2021-06-02 01:31 UTC, bvallelunga commented
Hey @agamm there are a couple of other products very loosely in the space (secrets management) but nothing directly in our category. Can we make an exception for this one case?

2021-06-02 23:10 UTC, agamm requested changes
I added 2 more products that seem to be closely related.

2021-06-02 23:10 UTC, agamm commented on README.md
> +
```suggestion
* [Envkey](https://www.envkey.com/) - Environment management with syncing mechanism for all apps.
```

2021-06-02 23:10 UTC, agamm commented on README.md
> +## Environment Variables
```suggestion
## Environment & Secret Management
```

2021-06-02 23:10 UTC, agamm commented on README.md
> +*Manage environment variables.*
```suggestion
*Manage environment variables and secrets for multiple apps or projects.*
* [Vault](https://www.vaultproject.io/) -  API driven secret key management.
```

2021-06-02 23:10 UTC, agamm commented on README.md
> +* [Doppler](https://doppler.com/) - All your environment variables across projects and environments, in one place.
```suggestion
* [Doppler](https://doppler.com/) - Environment variable management across projects, in one place.
* [1Password  Secrets Automation](https://1password.com/secrets/) - Secrets management with integration to 1Password.
```

2021-06-02 23:10 UTC, agamm commented on README.md
> +* [Environment Variables](#environment-variables)
```suggestion
* [Environment & Secret Management](#environment--secret-management)
```

2021-06-06 08:54 UTC, agamm approved these changes
Extra typos.

2021-06-06 08:54 UTC, agamm commented on README.md
> +* [Vault](https://www.vaultproject.io/) -  API driven secret key management.
```suggestion
* [Vault](https://www.vaultproject.io/) - API driven secret key management.
```

2021-06-06 08:54 UTC, agamm commented on README.md
> +* [1Password  Secrets Automation](https://1password.com/secrets/) - Secrets management with integration to 1Password.
```suggestion
* [1Password Secrets Automation](https://1password.com/secrets/) - Secrets management with integration to 1Password.
```

2021-06-06 08:54 UTC, merged