Add Depot to CI/CD tools
agamm/awesome-developer-first pull request #47
Opened 2022-11-29 15:50 UTC by kylegalbraith

Resources to read more about it:
https://depot.dev/docs#when-to-use-depot
https://depot.dev/docs/integrations/github-actions
https://depot.dev/#benchmarks

2022-12-26 15:28 UTC, agamm commented
Looks great! adding.

2022-12-26 15:30 UTC, agamm requested changes
I changed the description a bit to be less vague. Is it correct?

2022-12-26 15:30 UTC, agamm commented on README.md
> +* [Depot](https://depot.dev) - Build Docker images fast, in the cloud.
```suggestion
* [Depot](https://depot.dev) - Fast drop-in replacement to major docker images for your CI.
```

2022-12-26 15:30 UTC, agamm commented on README.md
> +* [Depot](https://depot.dev) - Build Docker images fast, in the cloud.
This feels more concrete, no?

2022-12-28 20:08 UTC, kylegalbraith commented on README.md
> +* [Depot](https://depot.dev) - Build Docker images fast, in the cloud.
I think `Drop-in replacement to build docker images faster in CI` is more accurate and concrete. Thoughts?

2022-12-29 22:35 UTC, agamm commented on README.md
> +* [Depot](https://depot.dev) - Build Docker images fast, in the cloud.
Great, change that and let's merge?

2023-01-03 09:30 UTC, kylegalbraith commented on README.md
> +* [Depot](https://depot.dev) - Build Docker images fast, in the cloud.
Done ✅

2023-01-03 19:08 UTC, agamm approved these changes
⚡

2023-01-03 19:09 UTC, merged