Add Linear
agamm/awesome-developer-first pull request #51
Opened 2023-01-31 11:08 UTC by fmerian

Linear is an issue and project tracking software built for developers.

2023-02-03 16:26 UTC, agamm requested changes
Better?

2023-02-03 16:26 UTC, agamm commented on README.md
> +* [Linear](https://linear.app/) - Issue tracking.
```suggestion
* [Linear](https://linear.app/) - Issue tracking built for developers.
```

2023-02-03 16:34 UTC, fmerian commented on README.md
> +* [Linear](https://linear.app/) - Issue tracking.
Much better :)

2023-02-04 22:52 UTC, agamm approved these changes
🔥

2023-02-04 22:52 UTC, merged