Adding SmartyStreets in the Geo section.
agamm/awesome-developer-first pull request #6
Opened 2021-04-27 23:20 UTC by SunSparc

The SmartyStreets US Reverse Geocoding API takes lat/long coordinates and transforms them into addresses. SmartyStreets does it super fast and super accurate.

2021-05-30 09:43 UTC, agamm commented
@SunSparc  Can we put `https://www.smartystreets.com/` instead so it includes all the other sub products (they also seem to be related to geo) ?

2021-06-02 12:03 UTC, SunSparc commented
@agamm, yes, certainly. That is a good idea. I will make that change.

2021-06-02 22:57 UTC, agamm requested changes
Better, as it encompasses more tools?

2021-06-02 22:57 UTC, agamm commented on README.md
> +* [SmartyStreets](https://www.smartystreets.com/) - US Reverse Geocoding API.
```suggestion
* [SmartyStreets](https://www.smartystreets.com/) - US Reverse Geocoding and Address Verification APIs.
```

2021-06-03 16:47 UTC, SunSparc reviewed
Yes, that is a good change. I like that.

2021-06-04 13:59 UTC, agamm approved these changes
Thanks for the suggestion!

2021-06-04 13:59 UTC, merged