Update README.md
agamm/awesome-developer-first pull request #62
Opened 2023-03-03 18:59 UTC by NathanTarbert

Add BoxyHQ to Authentication & Identity

2023-03-12 12:47 UTC, agamm commented
What are you competitors and how is BoxyHQ compare?

2023-03-15 06:06 UTC, agamm commented
Ok. Please add a full stop at the end of the sentence. And is it possible you also add workos?

2023-03-15 16:17 UTC, NathanTarbert commented
My bad for not adding the full stop at the end. I also added WorkOS and their tagline off of their website

2023-03-17 12:10 UTC, fmerian requested changes
hi @NathanTarbert, thanks for adding WorkOS, too.

can you make sure this new submission is sorted alphabetically please? 

thanks!

2023-03-17 13:08 UTC, NathanTarbert commented
You’re welcome, no problem. Will sort alphabetically

2023-03-17 16:07 UTC, NathanTarbert commented
Done!

2023-03-20 04:31 UTC, agamm requested changes
Looks good, but sort it alphabetically with WorkOS?

2023-03-20 04:31 UTC, agamm commented on README.md
> +* [WorkOS](https://workos.com/) - Enterprise SSO (and a whole lot more).
```suggestion
* [WorkOS](https://workos.com/) - Enterprise SSO and more out-of-the-box  enterprise features.
```

2023-03-20 13:12 UTC, NathanTarbert commented
Changed the description for WorkOS

2023-03-20 14:24 UTC, agamm approved these changes
Looks good!

2023-03-21 11:04 UTC, fmerian approved these changes

2023-03-23 20:42 UTC, NathanTarbert commented
Hi, just curious when this PR will be merged? thanks

2023-03-24 09:14 UTC, merged

2023-03-24 13:17 UTC, NathanTarbert commented
Thank you!