Add Neuledge
agamm/awesome-developer-first pull request #67
Opened 2023-03-15 17:00 UTC by moshest

2023-03-20 04:52 UTC, agamm requested changes
What about this?

2023-03-20 04:52 UTC, agamm commented on README.md
> +* [Neuledge](https://neuledge.com/) - Universal language for databases.
```suggestion
* [Neuledge](https://neuledge.com/) - Universal database agnostic language (abstract ORM).
```

2023-03-20 08:35 UTC, moshest commented
Sound good

2023-03-26 08:55 UTC, agamm approved these changes
LGTM!

2023-03-26 08:56 UTC, agamm commented
If you're at it we need to sort the list too from the changes...

2023-03-27 07:29 UTC, moshest commented
Done.. Please approve

2023-03-30 09:59 UTC, agamm approved these changes
Thanks again :)

2023-04-03 09:23 UTC, merged

2023-04-03 09:23 UTC, fmerian commented
welcome to the list, @moshest :)