Add Plain
agamm/awesome-developer-first pull request #78
Opened 2023-04-28 11:10 UTC by fmerian

https://plain.com/

2023-04-30 11:38 UTC, agamm requested changes
What about something more concrete?

2023-04-30 11:38 UTC, agamm commented on README.md
> +* [Plain](https://plain.com) - API-first customer service platform.
```suggestion
* [Plain](https://plain.com) - API-first customer service platform (support, feedback, rating widgets...).
```

2023-05-01 13:45 UTC, fmerian commented on README.md
> +* [Plain](https://plain.com) - API-first customer service platform.
LGTM :)

2023-05-06 07:21 UTC, agamm approved these changes
LGTM :)

2023-05-09 11:11 UTC, merged

2023-05-09 11:12 UTC, fmerian commented
ping @simonrohrbach @mattvagni for the record