Add Novu
agamm/awesome-developer-first pull request #94
Opened 2023-06-19 11:02 UTC by fmerian

https://novu.co/

## checklist

Please make sure you've complied with the [contribution guidelines](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md):
- [x] The homepage clearly states that the product is for developers.
  > "Headless", "API-First", "SaaS" are frequently used keywords.
  > Usually this means that the front page has some code examples :)
- [x] The product is available now and requires payment.
- [x] The PR has a descriptive title -- e.g., `Add {Product}`, not `Update README.md`.
- [x] The new submission isn't a duplicate.
- [x] The entry has a description, is sorted alphabetically, and ends with a full stop.

Thanks!

2023-06-28 08:58 UTC, agamm reviewed
What does "fully functional" mean in this context?

2023-06-28 10:31 UTC, fmerian commented
> What does "fully functional" mean in this context?

probably unnecessary

2023-07-03 16:49 UTC, agamm commented
"embedded" ? (sorry for being picky)

2023-07-11 05:50 UTC, fmerian commented
simplified description to:
```
Open-source notification infrastructure.
```
thoughts @agamm?

2023-07-11 08:57 UTC, agamm requested changes
WDYT?

2023-07-11 08:57 UTC, agamm commented on README.md
> +* [Novu](https://novu.co/) - Open-source notification infrastructure.
```suggestion
* [Novu](https://novu.co/) - Open-source notification (Email, SMS, Direct, and Push) management.
```

2023-07-12 10:45 UTC, agamm approved these changes
:+1:

2023-07-12 12:47 UTC, merged