Update README.md
agamm/awesome-developer-first pull request #95
Opened 2023-06-23 01:05 UTC by noashavit

Adding Aserto.com to the authentication and identity section. Aserto cloud-native SaaS that provides developers with an easy way to add fine-grained access control to their web applications. It works with every identity provide and framework, and is the only solution on the market that support every authorization model out of the box (RBAC, ABAC, PBAC, ReBAC and any other BAC :-))

[Insert URL to the product here.]

## checklist

Please make sure you've complied with the [contribution guidelines](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md):
- [ ] The homepage clearly states that the product is for developers.
  > "Headless", "API-First", "SaaS" are frequently used keywords.
  > Usually this means that the front page has some code examples :)
- [ ] The product is available now and requires payment.
- [ ] The PR has a descriptive title -- e.g., `Add {Product}`, not `Update README.md`.
- [ ] The new submission isn't a duplicate.
- [ ] The entry has a description, is sorted alphabetically, and ends with a full stop.

Thanks!

2023-06-23 07:37 UTC, fmerian requested changes
hi @noashavit, thanks for your first-time contribution!

how about a description that sounds a little less salesy (source: [GitHub](https://github.com/aserto-dev/topaz))?

also added a full-stop for consistency

2023-06-23 07:37 UTC, fmerian commented on README.md
> +* [Aserto](https://www.aserto.com) - Fine-grained authorization as a service
```suggestion
* [Aserto](https://www.aserto.com) - Cloud-native authorization for applications and APIs.
```

2023-06-26 15:26 UTC, noashavit commented on README.md
> +* [Aserto](https://www.aserto.com) - Fine-grained authorization as a service
looks good to me!

2023-06-27 09:18 UTC, fmerian approved these changes

2023-06-27 09:18 UTC, merged